spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_review_db
    username: postgres
    password: yaska23
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  application:
    name: movie-review-platform

server:
  port: 8080